name: New CC resource
description: Request to add a new CC resource
labels: ["new cc resource"]
body:
  - type: checkboxes
    id: rule
    attributes:
      label: Rules
      options:
        - label: "I know every resource I publish MUST NOT contain any of the default itemsadder resources (textures, models, .jar file)"
          required: true
  - type: textarea
    id: json
    attributes:
      label: JSON
      description: If you directly enter json configuration here, the following steps will be omitted
      placeholder: |-
        {
          "title": "<TITLE>",
          "premium": true | false,
          "link": "<LINK>",
          "image": "<LINK>",
          "tags": ["hat", "body", "ballon"],
          "author": "<NAME>"
        }
  - type: input
    id: title
    attributes:
      label: Resource name (title)
      description: The resource name (It will appear on the resource card title)
      placeholder: Amogus
  - type: checkboxes
    id: premium
    attributes:
      label: Is the resource premium (premium)
      options:
        - label: "yes"
  - type: input
    id: link
    attributes:
      label: Resource link (link)
      description: Resource link (The address will go to when user click the resource card)
      placeholder: "[link here]"
  - type: input
    id: image
    attributes:
      label: Resource cover (image)
      description: Resource cover (It will appear on the resource cover)
  - type: checkboxes
    id: tags
    attributes:
      label: Tags (tags)
      options:
        - label: "Hat"
          required: false
        - label: "Body"
          required: false
        - label: "Ballon"
          required: false
  - type: input
    id: name
    attributes:
      label: Your name (name)
      description: Author of the resource
  - type: markdown
    attributes:
      value: |
        ## Thanks for upload!