name: 新的IA资源
description: 申请上传IA资源
labels: ["new ia resource"]
body:
  - type: checkboxes
    id: rule
    attributes:
      label: 必读
      options:
        - label: "我知道我发布的资源内不得包含Itemsadder的默认资源（包括但不限于材质、模型、.jar文件）"
          required: true
        - label: "我知道我可以直接创建 Pull Request 提交写好的json文件，就不用在这里提交Issue了"
          required: true
  - type: input
    id: avatar
    attributes:
      label: 资源logo (avatar)
      description: 资源的logo图床链接 (It will appear on the resource card avatar)
  - type: input
    id: title
    attributes:
      label: 资源名称 (title)
      description: 资源的名称 (将会应用在资源卡的标题上)
      placeholder: CustomCrops ⭐ Create Crops Yourself ⭕ 1.16.4 - 1.19.2
  - type: input
    id: content
    attributes:
      label: 资源简介 (content)
      description: 资源的简介 (将会应用在资源的列表视图的名字下面)"
      placeholder: "Seasons, greenhouse, fertilizers and sprinklers! Supports ItemsAdder & Oraxen"
  - type: checkboxes
    id: premium
    attributes:
      label: 此资源是付费的吗？
      options:
        - label: "是的"
  - type: input
    id: link
    attributes:
      label: 资源链接 (link)
      description: 资源的链接 (其他人点击资源卡后会跳转的地方)
      placeholder: "[输入链接]"
  - type: input
    id: image
    attributes:
      label: 资源封面 (image)
      description: 资源的封面图床链接 (将会应用在资源卡的图像上)
  - type: checkboxes
    id: tags
    attributes:
      label: 标签 (tags)
      options:
        - label: "插件"
          required: false
        - label: "家具"
          required: false
        - label: "生物"
          required: false
        - label: "物品"
          required: false
        - label: "方块"
          required: false
        - label: "HUD"
          required: false
        - label: "GUI"
          required: false
  - type: input
    id: name
    attributes:
      label: 作者名字 (name)
      description: 资源的作者
  - type: markdown
    attributes:
      value: |
        ## 感谢投稿