name: 新的CC资源
description: 申请上传CC资源
labels: ["new cc resource"]
body:
  - type: checkboxes
    id: rule
    attributes:
      label: 必读
      options:
        - label: "我知道我发布的资源内不得包含Itemsadder的默认资源（包括但不限于材质、模型、.jar文件）"
          required: true
  - type: textarea
    id: json
    attributes:
      label: JSON
      description: 如果你直接在此输入json文件，后面的选项可以跳过
      placeholder: |-
        {
          "title": "<TITLE>",
          "premium": true | false,
          "link": "<LINK>",
          "image": "<LINK>",
          "tags": ["hat", "body", "ballon"],
          "author": "<NAME>"
        }
  - type: input
    id: title
    attributes:
      label: 资源名称 (title)
      description: 资源的名称 (将会应用在资源卡的标题上)
      placeholder: Amogus
  - type: checkboxes
    id: premium
    attributes:
      label: 此资源是付费的吗？
      options:
        - label: "是的"
  - type: input
    id: link
    attributes:
      label: 资源链接 (link)
      description: 资源的链接 (其他人点击资源卡后会跳转的地方)
      placeholder: "[输入链接]"
  - type: input
    id: image
    attributes:
      label: 资源封面 (image)
      description: 资源的封面图床链接 (将会应用在资源卡的图像上)
  - type: checkboxes
    id: tags
    attributes:
      label: 标签 (tags)
      options:
        - label: "帽子"
          required: false
        - label: "背包"
          required: false
        - label: "气球"
          required: false
        - label: "时装包"
          required: false
  - type: input
    id: name
    attributes:
      label: 作者名字 (name)
      description: 资源的作者
  - type: markdown
    attributes:
      value: |
        ## 感谢投稿