name: New IA resource
description: Request to add a new IA resource
labels: ["new ia resource"]
body:
  - type: checkboxes
    id: rule
    attributes:
      label: Rules
      options:
        - label: "I know every resource I publish MUST NOT contain any of the default itemsadder resources (textures, models, .jar file)"
          required: true
        - label: "I know I can create a Pull Request to submit the json file I wrote, so I don't need to submit an Issue here"
          required: true
  - type: textarea
    id: json
    attributes:
      label: JSON
      description: If you enter json configuration here, the following steps can be omitted
      placeholder: |-
        {
          "logo": "<LINK>",
          "image": "<LINK>",
          "title": "<TITLE>",
          "content": "<CONTENT>",
          "premium": true | false,
          "link": "<LINK>",
          "tags": ["plugin", "furniture", "entity", "item", "block", "hud", "gui"],
          "author": "<NAME>"
        }
  - type: input
    id: avatar
    attributes:
      label: Resource logo (avatar)
      description: Resource logo link(It will appear on the resource card avatar)
  - type: input
    id: title
    attributes:
      label: Resource name (title)
      description: The resource name (It will appear on the resource card title)
      placeholder: CustomCrops ⭐ Create Crops Yourself ⭕ 1.16.4 - 1.19.2
  - type: input
    id: content
    attributes:
      label: Resource introduction (content)
      description: "Introduction to resources (It will appear on the resource list)"
      placeholder: "Seasons, greenhouse, fertilizers and sprinklers! Supports ItemsAdder & Oraxen"
  - type: checkboxes
    id: premium
    attributes:
      label: Is the resource premium (premium)
      options:
        - label: "yes"
  - type: input
    id: link
    attributes:
      label: Resource link (link)
      description: Resource link (The address will go to when user click the resource card)
      placeholder: "[link here]"
  - type: input
    id: image
    attributes:
      label: Resource cover (image)
      description: Resource cover link (It will appear on the resource card cover)
  - type: checkboxes
    id: tags
    attributes:
      label: Tags (tags)
      options:
        - label: "Plugin"
          required: false
        - label: "Furniture"
          required: false
        - label: "Entity"
          required: false
        - label: "Item"
          required: false
        - label: "Block"
          required: false
        - label: "HUD"
          required: false
        - label: "GUI"
          required: false
  - type: input
    id: name
    attributes:
      label: Your name (name)
      description: Author of the resource
  - type: markdown
    attributes:
      value: |
        ## Thanks for upload!