name: Push to addon-station
on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  push_to_addon_station:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Commit files
        run: |
          git config --local user.email "actions[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git tag Sync
          git commit -a -m "Sync changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ADDON_STATION_TOKEN }}
          force: true
          repository: Cha-Shao/addon-station
          directory: src/resources
        env:
          GITHUB_REF: refs/tags/sync
